server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: UserManagementService
          uri: lb://UserManagementService
          predicates:
            - Path=/you-fit/v1/users/**
        - id: CenterManagementService
          uri: lb://CenterManagementService
          predicates:
            - Path=/you-fit/v1/centers/**
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
